services:
  postgres:
    image: postgres:15-alpine
    container_name: gestion-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gestion_proyectos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: gestion-minio
    environment:
      MINIO_ROOT_USER: admin_proconecta
      MINIO_ROOT_PASSWORD: superpassword123
    ports:
      - "9000:9000" # Puerto de la API
      - "9001:9001" # Puerto de la Consola web
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  backend:
    build:
      context: ./Backend
      target: development
    container_name: gestion-backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/gestion_proyectos
      PORT: 3001
      NODE_ENV: development
      JWT_SECRET: super_secreto_para_desarrollo_proconecta
      # Variables para conectar con MinIO
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: admin_proconecta
      MINIO_SECRET_KEY: superpassword123
      MINIO_BUCKET: proconecta-uploads
    volumes:
      - ./Backend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - minio

volumes:
  postgres_data:
  minio_data:
