services:
  postgres:
    image: postgres:15-alpine
    container_name: gestion-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gestion_proyectos
    ports:
      - "5433:5432" # Mapeo externo 5433 para tu laptop, interno 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gestion_proyectos"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: gestion-minio
    environment:
      MINIO_ROOT_USER: admin_proconecta
      MINIO_ROOT_PASSWORD: superpassword123
    ports:
      - "9000:9000" # API de MinIO
      - "9003:9001" # Consola de MinIO
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./Backend
      target: development
    container_name: gestion-backend
    # Cargamos las variables desde el archivo .env
    env_file:
      - ./Backend/.env
    environment:
      # Estas pueden quedarse aquí si son específicas del entorno Docker
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/gestion_proyectos
      MINIO_ENDPOINT: minio
    volumes:
      - ./Backend:/app
      - /app/node_modules
    ports: 
      - "3001:3001"
      - "5555:5555" # Puerto para Prisma Studio
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && npm run dev"

  frontend:
    build:
      context: ./Frontend
      target: development
    container_name: gestion-frontend
    environment:
      # URL para que el cliente Next.js encuentre al backend
      NEXT_PUBLIC_API_URL: http://localhost:3001
    volumes:
      - ./Frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "9002:9002"
    depends_on:
      - backend

volumes:
  postgres_data:
  minio_data:
