import type { User, Project } from './types';

export const mockUsers: User[] = [
  { 
    id: 'user-admin-1', 
    name: 'Usuario Administrador', 
    email: 'admin@cozcyt.dev', 
    password: 'password123',
    role: 'administrator', 
    avatarUrl: 'https://placehold.co/100x100',
    phone: '4921234567'
  },
  { 
    id: 'user-solicitante-1', 
    name: 'Dra. Elena Rodríguez', 
    email: 'elena.r@uaz.edu', 
    password: 'password123',
    role: 'solicitante', 
    avatarUrl: 'https://placehold.co/100x100',
    phone: '4929876543',
    company: 'Universidad Autónoma de Zacatecas',
    jobTitle: 'Investigadora Titular',
    activity: 'Investigación Biotecnológica'
  },
  { 
    id: 'user-student-1', 
    name: 'Emiliano De Santiago', 
    email: 'emidsm2005@gmail.com', 
    password: 'password123',
    role: 'estudiante', 
    avatarUrl: 'https://placehold.co/100x100',
    phone: '4921112233',
    municipality: 'Zacatecas',
    academicInstitution: 'Instituto Tecnológico de Zacatecas',
    career: 'Ingeniería en Sistemas Computacionales'
  },
  { 
    id: 'user-solicitante-2', 
    name: 'Ing. Jorge Ramírez', 
    email: 'jorge.r@itszac.edu.mx', 
    password: 'password123',
    role: 'solicitante', 
    avatarUrl: 'https://placehold.co/100x100',
    phone: '4923334455',
    company: 'ITSZ',
    jobTitle: 'Docente',
    activity: 'Educación Superior'
  }
];

export const mockProjects: Project[] = [
  {
    id: 'proj-001',
    title: 'Plataforma con IA para Agricultura Sostenible',
    description: 'Plataforma web para monitoreo de cultivos usando sensores IoT y análisis predictivo.',
    generalObjective: 'Desarrollar una herramienta accesible para pequeños agricultores que optimice el uso de agua.',
    expectedActivities: '1. Investigación de sensores. 2. Desarrollo de API. 3. Diseño de Dashboard.',
    category: 'Tecnología',
    status: 'En lista de espera',
    solicitante: mockUsers[1],
    requiredSkills: ['Python', 'React', 'IoT'],
    timeline: '6 meses',
    studentLimit: 4,
    studentsEnrolled: [mockUsers[2]],
    createdAt: '2025-01-15T10:00:00Z',
  },
  {
    id: 'proj-004',
    title: 'Módulo Interactivo de Física',
    description: 'Módulo web con simulaciones de física para nivel secundaria.',
    generalObjective: 'Facilitar el aprendizaje de leyes de Newton mediante gamificación.',
    expectedActivities: 'Diseño de niveles, programación de físicas en JS, pruebas con usuarios.',
    category: 'Educación',
    status: 'En revisión',
    solicitante: mockUsers[1],
    requiredSkills: ['JavaScript', 'Canvas', 'Física Básica'],
    timeline: '5 meses',
    studentLimit: 3,
    studentsEnrolled: [],
    createdAt: '2025-02-05T11:45:00Z',
  },
  {
    id: 'proj-005',
    title: 'Análisis de Contaminación Acústica',
    description: 'Mapa de calor de ruido urbano.',
    generalObjective: 'Identificar zonas críticas de ruido en el centro histórico.',
    expectedActivities: 'Toma de muestras, limpieza de datos, visualización con D3.js.',
    category: 'Planificación Urbana',
    status: 'Rechazado con retroalimentación',
    solicitante: mockUsers[3],
    requiredSkills: ['Data Science', 'Python'],
    timeline: '6 meses',
    studentLimit: 4,
    studentsEnrolled: [],
    feedback: 'El alcance es demasiado amplio para el tiempo propuesto.',
    createdAt: '2025-01-10T16:20:00Z',
  },
  {
    id: 'proj-007',
    title: 'Invernadero IoT',
    description: 'Sistema de riego automatizado.',
    generalObjective: 'Automatizar el cuidado de plantas domésticas.',
    expectedActivities: 'Circuitos con Arduino, App móvil simple.',
    category: 'IoT',
    status: 'Finalizado',
    solicitante: mockUsers[1],
    requiredSkills: ['Arduino', 'C++'],
    timeline: '2 meses',
    studentLimit: 1,
    studentsEnrolled: [mockUsers[2]],
    createdAt: '2024-11-01T10:00:00Z',
  },
];
